# Generated by Django 5.2 on 2025-05-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_ni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='mome',
            new_name='nome',
        ),
    ]
